### ISSUE TITLE
Missing language string 'text_title_list_edit'

### ISSUE THREAD

**Issue by chrissbarr** [openbaypro/OpenBay-Pro#32]
This might be a mistake/problem on my end, and if so I apologise in advance!

Running OC 2.0.3.2, OB v.3061.

I recently went to edit one of my eBay listing templates and was greeted with an error message at the top of the page:

![templateerror1](https://cloud.githubusercontent.com/assets/5538631/21520393/0462313c-cd44-11e6-9a86-583a80dc270c.PNG)

To my knowledge, I haven't changed anything to do with the OpenBay system recently, so I just assumed the error had always been there and I just hadn't noticed before. I went about editing the listing template, and then when I tried to save the changes I received the error:

![templateerror2](https://cloud.githubusercontent.com/assets/5538631/21520286/375b9d90-cd43-11e6-8084-3067d7667837.png)

Making it impossible to make and save any changes. I did a search for 'text_title_list_edit' in the OpenCart / OpenBay source, and I can only find the one reference in the ebay_template.php file. 

I'm assuming this is supposed to be a title for the template edit page that's just missing from the eay_template.php language file. Adding my own definition

    $_['text_title_list_edit']= 'Edit Listing Template';

seems to have fixed the problem, but I'm sure there must be more to it than that. The template edit page was working for me previously when I first set up my templates, and it must be working for everyone else too.

Am I going crazy? Is this a bug, has something changed here recently?

**Comment by jamesallsup** [comment]
@chrissbarr  - Nope, your not crazy :) Was a missing language var as you found, seems it has been there a while though so rare it hasn't been picked up before now.

The patch is on the current dev branch and will be included in the next update for the affected versions.

Thanks, James
